# Site settings
title: Ben Mildren
email: mildrenben@gmail.com
description: Ben Mildren. Web Designer and Developer.
baseurl: "/benmildren/" # the subpath of your site, e.g. /blog/
url: "https://mildrenben.github.io/benmildren/" # the base hostname & protocol for your site
twitter_username: mildrenben
github_username: mildrenben
gems: [jekyll-paginate]
paginate: 6
paginate_path: "blog/page:num/"

# Build settings
markdown: kramdown
