# Site settings
title: Ben Mildren
email: mildrenben@gmail.com
description: Ben Mildren. Web Designer and Developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://benmildren.com" # the base hostname & protocol for your site
twitter_username: mildrenben
github_username: mildrenben
paginate: 6
paginate_path: "blog/page:num/"

# Build settings
markdown: kramdown
