name: Build

on: push

jobs:
  build:
    name: Run gulp to build the code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 7.10.0

      - name: Install node packages
        run: npm i

      - name: Run gulp
        run: gulp
