name: Build

on: push

jobs:
  build:
    name: Run gulp to build the code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node and node packages
        uses: actions/setup-node@v1
        run: npm i

      - name: Run gulp
        run: gulp
